/**
 * Auto-name each conversation from its first user message, so the browser
 * sidebar can show something better than "New conversation". pi exposes the
 * name over ACP as the session title (session/list), which the control plane
 * snoops off the proxied stream.
 *
 * The title is generated by the same model the conversation uses (the hakanai
 * provider), called in-process via completeSimple. This is the egress-locked
 * deployment's only model, and it is free/local, so reusing it is fine.
 *
 * Adapted from the author's dotfiles extension; see there for why we call
 * completeSimple directly rather than shelling out to `pi -p`.
 */
import type { ExtensionAPI, ExtensionContext, ModelRegistry } from "@earendil-works/pi-coding-agent";
import { completeSimple } from "@earendil-works/pi-ai";

function resolveModel(registry: ModelRegistry) {
  const want = process.env.HAKANAI_MODEL || "default";
  return registry.find("hakanai", want) ?? undefined;
}

export default function (pi: ExtensionAPI) {
  let named = false;

  pi.on("session_start", async () => {
    named = !!pi.getSessionName();
  });

  // Best-effort and detached, so the agent loop never waits on the extra call.
  pi.on("agent_end", (event, ctx: ExtensionContext) => {
    if (named || pi.getSessionName()) return;
    named = true; // prevent retries on later turns

    const userMsg = event.messages.find((m) => m.role === "user");
    if (!userMsg) return;
    const text =
      typeof userMsg.content === "string"
        ? userMsg.content
        : userMsg.content
            .filter((b) => b.type === "text")
            .map((b) => (b as { text: string }).text)
            .join(" ");
    if (!text) return;

    void (async () => {
      try {
        const model = resolveModel(ctx.modelRegistry);
        if (!model) return;
        const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
        if (!auth.ok || !auth.apiKey) return;

        const result = await completeSimple(
          model,
          {
            messages: [
              {
                role: "user",
                content: [
                  {
                    type: "text",
                    text: `Generate a brief session title (max 50 chars, no quotes) for this message:\n\n${text.slice(0, 500)}`,
                  },
                ],
                timestamp: Date.now(),
              },
            ],
          },
          { apiKey: auth.apiKey, headers: auth.headers, maxTokens: 64, temperature: 0 },
        );

        const title = result.content
          .filter((b) => b.type === "text")
          .map((b) => (b as { text: string }).text)
          .join(" ")
          .trim()
          .replace(/^["']|["']$/g, "")
          .slice(0, 50);
        if (title && !pi.getSessionName()) pi.setSessionName(title);
      } catch {
        // Naming is best-effort; ignore failures.
      }
    })();
  });
}
